// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bdqKdnXkIqQ5MlMuIKT5ObXEIaGV1Ww',
    appId: '1:56088354024:web:96b4d3749ba652a9087d5d',
    messagingSenderId: '56088354024',
    projectId: 'stake-grow-app',
    authDomain: 'stake-grow-app.firebaseapp.com',
    storageBucket: 'stake-grow-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeob8WWkJVm3NcwXwbaEGM1IijmOa2lo8',
    appId: '1:56088354024:android:27f4b6bf985fc77d087d5d',
    messagingSenderId: '56088354024',
    projectId: 'stake-grow-app',
    storageBucket: 'stake-grow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkexRe_bgFqsg0yvHQX5lwsO27d4aZLWw',
    appId: '1:56088354024:ios:894c850f6adcbd65087d5d',
    messagingSenderId: '56088354024',
    projectId: 'stake-grow-app',
    storageBucket: 'stake-grow-app.firebasestorage.app',
    iosBundleId: 'com.example.stakeGrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkexRe_bgFqsg0yvHQX5lwsO27d4aZLWw',
    appId: '1:56088354024:ios:894c850f6adcbd65087d5d',
    messagingSenderId: '56088354024',
    projectId: 'stake-grow-app',
    storageBucket: 'stake-grow-app.firebasestorage.app',
    iosBundleId: 'com.example.stakeGrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-bdqKdnXkIqQ5MlMuIKT5ObXEIaGV1Ww',
    appId: '1:56088354024:web:7bab8ec98599ed05087d5d',
    messagingSenderId: '56088354024',
    projectId: 'stake-grow-app',
    authDomain: 'stake-grow-app.firebaseapp.com',
    storageBucket: 'stake-grow-app.firebasestorage.app',
  );
}
